### ISSUE TITLE
Unexpected: Toc extension replaces some characters by html entities

### ISSUE THREAD

**Issue by laurentj** [carew/carew#35]
In generated web pages, all accented characters are replaced by html entities. This is useless when the html web page is UTF-8 encoded, and it makes the page more heavy.

It seems that the toc extension is responsible of this unexpected behavior, or more precisely, the responsible is htmltools helpers.

And there is no way to disable the toc extension, a feature that I don't need.

**Comment by lyrixx** [comment]
Hi @laurentj 

Thanks for this feedback.

Actually, all non-ascii char are replaced by the `DomDocument` class.

How I can I fix your issue?
I could add a flag / option to not build the TOC ?

**Comment by laurentj** [comment]
I tried many things yesterday, and I didn't find a solution with DomDocument to disable the convertion to html entities..

The only thing I made is a plugin for carew, which is called after the toc plugin, and which does an html_entities_decode on the document body.

So probably you could call html_entities_decode in the toc plugin.

```
$document->setBody(html_entity_decode($body,ENT_QUOTES,"UTF-8"));
```

And additionally, we could also have some settings to disable some core extensions. I'll open a new issue.
